server:
  port: 10086
spring:
  application:
    name: leu-eureka  #作为微服务名称注入到eureka

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    registry-fetch-interval-seconds: 5
    eureka-connection-idle-timeout-seconds: 5
  server:
#    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 5000 #定期清除无效连接