server:
  port: 80

spring:
  application:
    name: leu-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
    fetch-registry: true #拉取服务列表
    registry-fetch-interval-seconds: 5 #拉取服务间隔时间
  instance:
    lease-expiration-duration-in-seconds: 5 # 过期时间
    lease-renewal-interval-in-seconds: 5 # 心跳时间

feign:
  hystrix:
    enabled: true #开启feign熔断功能