server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/leu?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  application:
    name: leu-provider #作为微服务名称注入到eureka

mybatis:
  type-aliases-package: com.liang.com.leu.pojo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka/
    register-with-eureka: true #服务提供方启动时会检测改参数是否为true，true-注册给eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳时间
    lease-expiration-duration-in-seconds: 5 #过期时间

logging:
  level:
   com.liang.com.leu.mapper : debug #打印sql语句